export const DOV_SCHEMA_VERSION = 19;
export const LLM_INSTRUCTIONS_START = `<!-- dov-start v${DOV_SCHEMA_VERSION} -->`;
export const LLM_INSTRUCTIONS_END = `<!-- dov-end -->`;
export const LLM_INSTRUCTIONS_MARKER = LLM_INSTRUCTIONS_START;
export const DOV_SKILL_VERSION_MARKER = `<!-- dov-skill v${DOV_SCHEMA_VERSION} -->`;
const DEFAULT_EXTENSION_ID = '<installed-extension-id>';

export interface DovInstructionOptions {
	extensionId?: string;
}

// Matches any version of the dov block (v1, v2, …)
export const DOV_BLOCK_REGEX = /<!-- dov-start v\d+ -->[\s\S]*?<!-- dov-end -->/g;
// Also match the old v1 marker that had no end tag
export const DOV_LEGACY_REGEX = /<!-- document-oriented-vibing(?:-v\d+)?[\s-]*-->[\s\S]*$/;

function getCaptureReviewCommand(reviewName: string, options: DovInstructionOptions = {}): string {
	const extensionId = options.extensionId?.trim() || DEFAULT_EXTENSION_ID;
	return `code --open-url "vscode://${extensionId}/captureReview?name=${reviewName}&threadId=$CODEX_THREAD_ID"`;
}

export function getLlmInstructions(options: DovInstructionOptions = {}): string {
	const captureReviewCommand = getCaptureReviewCommand('<kebab-case-title>.diff', options);
	return [
		'',
		LLM_INSTRUCTIONS_START,
		'## Feature Diagrams (document-oriented-vibing)',
		'',
		'This project uses a VS Code extension to plan features as diagrams.',
		'Features are `.md` files in `.features/` at the workspace root.',
		'The extension auto-opens the diagram when a new file is created.',
		'',
		'Reviews are raw `.diff` files in `.reviews/` at the workspace root.',
		'The extension auto-opens diagrams and reviews when new files are created.',
		'',
		'**IMPORTANT: Only create `.features/*.md` files when the user says `+plan` or `+show`.**',
		'Only create `.reviews/*.diff` files when the user says `+review`.',
		'If none of those modes are specified, do NOT create a feature or review file.',
		'',
		'### Modes',
		'',
		'- **`+plan`** — Diagram only. Placeholder file paths. No source code.',
		'- **`+show`** — Write code first, then diagram with real paths.',
		'- **`+review`** — After code edits are complete, open the DOV capture URI with the editor CLI.',
		'',
		'### File format',
		'',
		'Use the compact DOV diagram syntax (NOT mermaid). The extension translates it automatically.',
		'',
		'```',
		'# Feature: <title>',
		'',
		'## Diagram',
		'',
		'```dov',
		'<DOV diagram>',
		'```',
		'',
		'## Summary',
		'<intent, constraints, behavior>',
		'',
		'## Details',
		'- **NodeName**: hover tooltip text',
		'```',
		'',
		'### Review file format',
		'',
		'When the user says `+review`, open the DOV capture URI only after all requested code edits are complete.',
		'`+review` builds the review from changes recorded in the current chat/session, so running it before editing code will miss the later changes.',
		'',
		`Run \`${captureReviewCommand}\`.`,
		'This opens a VS Code URI and requires GUI access. If running in a sandbox, request outside-sandbox/escalated execution up front.',
		'Do not treat exit code 0 alone as proof that the extension opened; Electron/macOS may print GUI handoff errors such as `task_name_for_pid` even when the CLI exits 0.',
		'After running the URI command, verify `.reviews/<name>.diff` exists before saying the review opened.',
		'',
		'The extension creates `.reviews/` if needed, writes `.reviews/<name>.diff`, and opens the DOV review panel.',
		'Do not write review summaries, JSON, findings, status fields, or other metadata unless the user explicitly asks for a structured review.',
		'',
		'### DOV syntax',
		'',
		'Header: `flow LR` (or TD/RL/BT). Also: `seq`, `class`, `state`, `er`.',
		'',
		'Nodes (defined inline on first use):',
		'- `Name[Label|path/to/file.ts:line]` — rectangle',
		'- `Name{Label|path/to/file.ts}` — diamond (decision)',
		'- `Name(Label)` — rounded/stadium',
		'- `Name:Label text` — plain rounded',
		'',
		'`|` separates label lines. Include file paths to make nodes clickable.',
		'Append `:lineNumber` to jump to a specific line.',
		'',
		'**CRITICAL: File paths MUST be the full relative path from the workspace root.**',
		'Use `src/auth/controller.ts`, NOT `controller.ts` or `auth/controller.ts`.',
		'The extension resolves paths from the workspace root — partial paths will not open.',
		'',
		'Edges:',
		'- `A >label> B` — edge with label',
		'- `A > B` — edge without label',
		'',
		'Sequence diagrams:',
		'- `A ->label-> B` — solid arrow',
		'- `A --label--> B` — dashed arrow',
		'',
		'### Example',
		'',
		'```',
		'# Feature: user login',
		'',
		'## Diagram',
		'',
		'```dov',
		'flow LR',
		'Client(Browser) >POST /login> Auth[AuthController|src/auth/controller.ts:15]',
		'Auth >credentials> Validate{validateCredentials|src/auth/validate.ts:8}',
		'Validate >valid user> Token[issueJWT|src/auth/token.ts:22]',
		'Validate >invalid> Err:401 Unauthorized',
		'Token >JWT string> Auth',
		'Auth >audit event> Log[logAttempt|src/auth/audit.ts:5]',
		'```',
		'',
		'## Summary',
		'Authenticate with email/password, return a JWT, and log the attempt.',
		'',
		'## Details',
		'- **Auth**: Express POST handler, validates body, delegates to services.',
		'- **Validate**: bcrypt comparison, returns User or null.',
		'- **Token**: Signs RS256 token, 24h expiry, userId + role claims.',
		'- **Log**: Writes to audit_log for success and failure.',
		'```',
		'',
		LLM_INSTRUCTIONS_END,
		'',
	].join('\n');
}

export function getCodexAgentsInstructions(options: DovInstructionOptions = {}): string {
	const captureReviewCommand = getCaptureReviewCommand('<kebab-case-title>.diff', options);
	const exampleCaptureReviewCommand = getCaptureReviewCommand('auth-review.diff', options);
	return [
		'',
		LLM_INSTRUCTIONS_START,
		'## Document Oriented Vibing',
		'',
		'This project uses DOV feature diagrams.',
		'',
		'When the user uses `+plan`, `+show`, `+review`, asks for a feature diagram or code review, or works with `.features/*.md`, `.reviews/*.diff`, or `.reviews/*.json`, use the `document-oriented-vibing` skill.',
		'The repo-scoped skill is stored at `.agents/skills/document-oriented-vibing/SKILL.md`.',
		'',
		'Do not create `.features/*.md` files unless the user explicitly uses `+plan` or `+show`.',
		'Do not create `.reviews/*.diff` files unless the user explicitly uses `+review`.',
		'Do not create `.reviews/*.json` files unless the user explicitly asks for a structured DOV review.',
		'',
		`For \`+review\`, after all requested code edits are complete, run \`${captureReviewCommand}\`, such as \`${exampleCaptureReviewCommand}\`.`,
		'`+review` builds the review from changes recorded in the current chat/session, so running it before editing code will miss the later changes.',
		'This opens a VS Code URI and requires GUI access. If running in a sandbox, request outside-sandbox/escalated execution up front.',
		'Do not treat exit code 0 alone as proof that the extension opened; Electron/macOS may print GUI handoff errors such as `task_name_for_pid` even when the CLI exits 0.',
		'After running the URI command, verify `.reviews/<name>.diff` exists before saying the review opened. If verification fails or outside-sandbox execution is rejected, say the review could not be reliably opened.',
		'The extension creates `.reviews/` if needed, writes the review diff, and opens DOV review.',
		'Do not manually write `.reviews/*.diff` or run `git diff` unless the user explicitly asks.',
		'Do not summarize the diff or write extra review metadata unless the user explicitly asks.',
		'DOV saves approve/reject state itself in a sibling `.state.json` file as the user reviews hunks.',
		LLM_INSTRUCTIONS_END,
		'',
	].join('\n');
}

export function getDovSkillInstructions(options: DovInstructionOptions = {}): string {
	const captureReviewCommand = getCaptureReviewCommand('<kebab-case-title>.diff', options);
	const exampleCaptureReviewCommand = getCaptureReviewCommand('example-review.diff', options);
	return [
		'---',
		'name: "document-oriented-vibing"',
		'description: "Use when the user says +plan, +show, or +review, asks for a feature diagram or code review, creates or edits .features/*.md, .reviews/*.diff, or .reviews/*.json, or needs a DOV architecture diagram with clickable file paths."',
		'---',
		'',
		DOV_SKILL_VERSION_MARKER,
		'',
		'# Document Oriented Vibing',
		'',
		'Use this workflow for DOV feature diagrams in this repository.',
		'',
		'## Modes',
		'',
		'- `+plan`: create or update only `.features/*.md`. Use plausible placeholder file paths. Do not write source code.',
		'- `+show`: write the requested code first, then create or update `.features/*.md` with real file paths pointing to the code.',
		`- \`+review\`: after code edits are complete, run \`${captureReviewCommand}\`. Do not summarize, review, or apply changes yourself.`,
		'- Without `+plan`, `+show`, or `+review`: do not create `.features/*.md`, `.reviews/*.diff`, or `.reviews/*.json` unless the user explicitly asks for a DOV feature diagram or DOV review.',
		'',
		'## Workflow',
		'',
		'1. Put feature diagrams in `.features/` at the workspace root.',
		'2. Use the compact DOV diagram syntax, not Mermaid syntax.',
		'3. Include full relative paths from the workspace root in clickable nodes, such as `src/auth/controller.ts:15`.',
		'4. Add `## Summary` and `## Details` sections when useful for review.',
		'5. For exact syntax and examples, read `references/schema.md`.',
		'6. For `+review`, finish the requested code edits first, then follow the raw diff workflow in `references/review-schema.md`.',
		'',
		'## Review Workflow',
		'',
		`When the user says \`+review\`, run \`${captureReviewCommand}\`, such as \`${exampleCaptureReviewCommand}\`, only after all requested code edits are complete.`,
		'`+review` builds the review from changes recorded in the current chat/session, so running it before editing code will miss the later changes.',
		'This opens a VS Code URI and requires GUI access. If running in a sandbox, request outside-sandbox/escalated execution up front.',
		'Do not treat exit code 0 alone as proof that the extension opened; Electron/macOS may print GUI handoff errors such as `task_name_for_pid` even when the CLI exits 0.',
		'After running the URI command, verify `.reviews/<name>.diff` exists before saying the review opened. If verification fails or outside-sandbox execution is rejected, say the review could not be reliably opened.',
		'The extension creates `.reviews/` if needed, writes the review diff, and opens the DOV review panel.',
		'If URI opening is unavailable, tell the user instead of writing a fallback diff.',
		'DOV saves approve/reject state itself in a sibling `.state.json` file as the user reviews hunks.',
		'',
		'## Output Rules',
		'',
		'- Keep diagrams reviewable and focused on the requested feature.',
		'- Prefer real file paths in `+show`; use placeholder paths only in `+plan`.',
		'- Never prefix paths with `@`.',
		'- Append `:lineNumber` when a precise line target is known.',
		'- Keep `.reviews/*.diff` as raw git output only; do not format or summarize it.',
		'',
	].join('\n');
}

export function getReviewSchemaDocument(options: DovInstructionOptions = {}): string {
	const captureReviewCommand = getCaptureReviewCommand('<kebab-case-title>.diff', options);
	return [
		'# DOV Review File',
		'',
		'When the user says `+review`, open the DOV capture URI after all requested code edits are complete.',
		'`+review` builds the review from changes recorded in the current chat/session, so running it before editing code will miss the later changes.',
		'The extension writes a raw scoped git diff file in `.reviews/` and opens it as a review page.',
		'',
		'## File Path',
		'',
		'Pass a `.diff` file name as the URI `name` query parameter, such as `name=auth-review.diff`. The extension writes `.reviews/<name>.diff`.',
		'',
		'## Diff Capture',
		'',
		`Run \`${captureReviewCommand}\` from the workspace root.`,
		'This opens a VS Code URI and requires GUI access. If running in a sandbox, request outside-sandbox/escalated execution up front.',
		'Do not treat exit code 0 alone as proof that the extension opened; Electron/macOS may print GUI handoff errors such as `task_name_for_pid` even when the CLI exits 0.',
		'After running the URI command, verify `.reviews/<name>.diff` exists before saying the review opened.',
		'',
		'The extension creates `.reviews/` if needed, writes the review diff, and opens the DOV review panel.',
		'Do not manually write the diff or run `git diff` unless the user explicitly asks.',
		'DOV saves approve/reject state itself in a sibling `.state.json` file as the user reviews hunks.',
		'',
		'## Rules',
		'',
		'- Keep the file as raw git output only.',
		'- Do not summarize the diff, write findings, or add metadata unless the user explicitly asks.',
		'- Do not create `.reviews/*.json` unless the user explicitly asks for a structured DOV review.',
		'',
	].join('\n');
}

export function getDovSkillOpenaiYaml(): string {
	return [
		'interface:',
		'  display_name: "Document Oriented Vibing"',
		'  short_description: "Create DOV feature diagrams for code plans"',
		'  default_prompt: "Use $document-oriented-vibing to plan this feature as a DOV diagram."',
		'',
		'policy:',
		'  allow_implicit_invocation: true',
		'',
	].join('\n');
}

export function getSchemaDocument(): string {
	return [
		'# Feature Diagram Schema',
		'',
		'Feature files use DOV syntax — a compact diagram format translated to Mermaid by the extension.',
		'',
		'## DOV syntax reference',
		'',
		'Header: `flow LR` | `seq` | `class` | `state` | `er`',
		'',
		'Nodes: `Name[Label|path.ts]` (rect), `Name{Label|path.ts}` (diamond), `Name(Label)` (rounded), `Name:Label` (plain)',
		'',
		'Edges: `A >label> B` (labeled), `A > B` (unlabeled)',
		'',
		'Sequence: `A ->label-> B` (solid), `A --label--> B` (dashed)',
		'',
		'`|` separates label lines. Include file paths for clickable nodes. Append `:line` for line numbers.',
		'',
		'**File paths must be the full relative path from the workspace root** (e.g. `src/auth/controller.ts`).',
		'',
		'## Example',
		'',
		'```',
		'# Feature: user login',
		'',
		'## Diagram',
		'',
		'```dov',
		'flow LR',
		'Client(Browser) >POST /login> Auth[AuthController|src/auth/controller.ts:15]',
		'Auth >credentials> Validate{validateCredentials|src/auth/validate.ts:8}',
		'Validate >valid> Token[issueJWT|src/auth/token.ts:22]',
		'Validate >invalid> Err:401 Unauthorized',
		'Token >JWT> Auth',
		'Auth >audit> Log[logAttempt|src/auth/audit.ts:5]',
		'```',
		'',
		'## Summary',
		'Authenticate with email/password, return a JWT, log the attempt.',
		'',
		'## Details',
		'- **Auth**: POST handler, validates body, delegates.',
		'- **Validate**: bcrypt comparison, returns User or null.',
		'```',
		'',
	].join('\n');
}

export function createFeatureTemplate(featureFileName: string): string {
	const title = featureFileName.replace(/\.md$/i, '').replace(/-/g, ' ');
	return [
		`# Feature: ${title}`,
		'',
		'## Diagram',
		'',
		'```dov',
		'flow LR',
		'Start(Start) > Step[Step 1|src/example.ts]',
		'Step > End(End)',
		'```',
		'',
		'## Summary',
		'Describe intent, constraints, and expected behavior.',
		'',
	].join('\n');
}
