export const DOV_SCHEMA_VERSION = 1;
export const LLM_INSTRUCTIONS_START = `<!-- dov-start v${DOV_SCHEMA_VERSION} -->`;
export const LLM_INSTRUCTIONS_END = `<!-- dov-end -->`;
export const LLM_INSTRUCTIONS_MARKER = LLM_INSTRUCTIONS_START;

// Matches any version of the dov block (v1, v2, …)
export const DOV_BLOCK_REGEX = /<!-- dov-start v\d+ -->[\s\S]*?<!-- dov-end -->/g;
// Also match the old v1 marker that had no end tag
export const DOV_LEGACY_REGEX = /<!-- document-oriented-vibing(?:-v\d+)?[\s-]*-->[\s\S]*$/;

export function getLlmInstructions(): string {
	return [
		'',
		LLM_INSTRUCTIONS_START,
		'## Feature Diagrams (document-oriented-vibing)',
		'',
		'This project uses a VS Code extension called **document-oriented-vibing** to plan features as Mermaid diagrams.',
		'Features are stored as `.md` files in the `.features/` folder at the workspace root.',
		'',
		'**IMPORTANT: When building a feature, ALWAYS create or update the corresponding `.features/*.md` file first.**',
		'The extension opens a live Mermaid preview panel.',
		'The preview auto-updates when the file changes — just write the file and the user sees the diagram immediately.',
		'',
		'### Workflow modes',
		'',
		'The user will prefix their request with a mode keyword:',
		'',
		'- **`+plan`** — Plan only. Create/update the `.features/*.md` diagram showing the architecture,',
		'  components, and data flow. Use placeholder file paths for where code *would* go.',
		'  **Do NOT write any source code.** Just the diagram and summary.',
		'  The user will review the diagram and iterate before any code is written.',
		'',
		'- **`+show`** — Build and show. Write the actual source code files first, then create/update',
		'  the `.features/*.md` diagram with the real file paths pointing to the code you just wrote.',
		'  The diagram should reflect the implementation as-built.',
		'',
		'If neither `+plan` nor `+show` is specified, do NOT create a `.features/*.md` file.',
		'Only create feature diagrams when the user explicitly uses one of these modes.',
		'',
		'### Opening the diagram automatically',
		'',
		'The extension watches the `.features/` folder. When a new `.md` file is created,',
		'the diagram preview opens automatically — no shell command needed.',
		'Just create the file and the user will see the diagram.',
		'',
		'### How to create a feature file',
		'',
		'1. Make sure `.features/` exists at the workspace root. Create it if not.',
		'2. Create a `.md` file inside `.features/` (e.g. `.features/user-login.md`).',
		'3. Use the exact format below. The diagram comes first.',
		'4. Tell the user: "Open the diagram with `DOV: Home` (Ctrl/Cmd+Shift+P) and click your feature."',
		'',
		'### File format',
		'',
		'```',
		'# Feature: <title>',
		'',
		'## Diagram',
		'',
		'```mermaid',
		'<any valid Mermaid diagram>',
		'```',
		'',
		'## Summary',
		'<describe intent, constraints, expected behavior>',
		'',
		'## Details',
		'- **NodeName**: what this node does, edge cases, error handling, etc.',
		'- **AnotherNode**: more context about this node.',
		'```',
		'',
		'### Supported Mermaid diagram types',
		'',
		'- `flowchart` / `graph` — system architecture, data flow, component relationships',
		'- `sequenceDiagram` — API calls, protocol flows, async interactions',
		'- `classDiagram` — data models, interfaces, type hierarchies',
		'- `stateDiagram-v2` — state machines, lifecycle transitions',
		'- `erDiagram` — database schemas, entity relationships',
		'- `journey` — user journey maps',
		'- `gantt` — project timelines',
		'',
		'### File path linking (clickable nodes)',
		'',
		'Nodes become clickable in the preview when they contain file paths.',
		'Put the relative file path in the node label (e.g. `src/auth/controller.ts`).',
		'Clicking a node in the diagram opens that file in VS Code.',
		'',
		'- For files that exist: use the real path.',
		'- For files that don\'t exist yet: use the planned path — the LLM or user will create it later.',
		'- Use `\\n` in labels to put the function/service name on one line and the file path on the next.',
		'- **Do NOT prefix paths with `@`.** Just use bare relative paths.',
		'- **Line numbers**: append `:lineNumber` to jump to a specific line, e.g. `src/auth/controller.ts:42`.',
		'  This opens the file and scrolls to that line.',
		'',
		'### Rules',
		'',
		'- Use standard Mermaid syntax. Any valid Mermaid diagram is accepted.',
		'- Always include file paths in node labels so nodes are clickable.',
		'- `## Diagram` and `## Summary` are required. `## Details` is optional but encouraged.',
		'- `## Details` maps node names to descriptions. Format: `- **NodeName**: description`.',
		'  These appear as hover tooltips on diagram nodes.',
		'- **Never use `@` before file paths** — it conflicts with Mermaid syntax.',
		'- Be descriptive: label edges with what data flows through them.',
		'',
		'### Example',
		'',
		'```',
		'# Feature: user login',
		'',
		'## Diagram',
		'',
		'```mermaid',
		'flowchart LR',
		'    Client([Browser]) -->|POST /login with email+password| Auth["AuthController\\nsrc/auth/controller.ts:15"]',
		'    Auth -->|credentials| Validate{"validateCredentials\\nsrc/auth/validate.ts:8"}',
		'    Validate -->|valid user| Token["issueJWT\\nsrc/auth/token.ts:22"]',
		'    Validate -->|invalid| Err([401 Unauthorized])',
		'    Token -->|JWT string| Auth',
		'    Auth -->|audit event| Log["logAttempt\\nsrc/auth/audit.ts:5"]',
		'```',
		'',
		'## Summary',
		'Authenticate with email/password, return a JWT, and log the attempt.',
		'',
		'## Details',
		'- **AuthController**: Express route handler at POST /api/auth/login. Validates request body, delegates to services.',
		'- **validateCredentials**: bcrypt comparison against users table. Returns User or null.',
		'- **issueJWT**: Signs RS256 token with 24h expiry, includes userId and role claims.',
		'- **logAttempt**: Writes to audit_log table for both success and failure. Includes IP and user agent.',
		'```',
		'',
		LLM_INSTRUCTIONS_END,
		'',
	].join('\n');
}

export function getSchemaDocument(): string {
	return [
		'# Feature Diagram Schema',
		'',
		'This folder contains feature files (`*.md`). Each file describes one feature using a [Mermaid](https://mermaid.js.org/) diagram.',
		'',
		'A VS Code extension renders them as live diagrams in a preview panel.',
		'',
		'## File format',
		'',
		'```',
		'# Feature: <title>',
		'',
		'## Diagram',
		'',
		'```mermaid',
		'<any valid Mermaid diagram syntax>',
		'```',
		'',
		'## Summary',
		'<free-text description of intent, constraints, expected behavior>',
		'',
		'## Details',
		'- **NodeName**: hover tooltip description for this node.',
		'```',
		'',
		'## Supported diagram types',
		'',
		'| Type | Use case |',
		'|------|----------|',
		'| `flowchart` / `graph` | System architecture, data flow, component relationships |',
		'| `sequenceDiagram` | API calls, protocol flows, async interactions |',
		'| `classDiagram` | Data models, interfaces, type hierarchies |',
		'| `stateDiagram-v2` | State machines, lifecycle transitions |',
		'| `erDiagram` | Database schemas, entity relationships |',
		'| `journey` | User journey maps |',
		'| `gantt` | Project timelines |',
		'',
		'## File path linking',
		'',
		'Nodes become clickable when they contain file paths.',
		'Use bare relative paths like `src/foo/bar.ts` in node labels.',
		'Append `:lineNumber` to jump to a specific line (e.g. `src/foo/bar.ts:42`).',
		'Clicking opens that file in VS Code.',
		'**Do not prefix paths with `@`** — it conflicts with Mermaid syntax.',
		'',
		'## Example',
		'',
		'```',
		'# Feature: user login',
		'',
		'## Diagram',
		'',
		'```mermaid',
		'flowchart LR',
		'    Client([Browser]) -->|POST /login with email+password| Auth["AuthController\\nsrc/auth/controller.ts:15"]',
		'    Auth -->|credentials| Validate{"validateCredentials\\nsrc/auth/validate.ts:8"}',
		'    Validate -->|valid user| Token["issueJWT\\nsrc/auth/token.ts:22"]',
		'    Validate -->|invalid| Err([401 Unauthorized])',
		'    Token -->|JWT string| Auth',
		'    Auth -->|audit event| Log["logAttempt\\nsrc/auth/audit.ts:5"]',
		'```',
		'',
		'## Summary',
		'Authenticate a user with email/password, return a JWT, and log the attempt.',
		'',
		'## Details',
		'- **AuthController**: POST handler, validates body, delegates to auth services.',
		'- **validateCredentials**: bcrypt hash comparison, returns User or null.',
		'- **issueJWT**: Signs RS256 token with 24h expiry, userId + role claims.',
		'- **logAttempt**: Writes success/failure to audit_log with IP and user agent.',
		'```',
		'',
	].join('\n');
}

export function createFeatureTemplate(featureFileName: string): string {
	const title = featureFileName.replace(/\.md$/i, '').replace(/-/g, ' ');
	return [
		`# Feature: ${title}`,
		'',
		'## Diagram',
		'',
		'```mermaid',
		'flowchart LR',
		'    A([Start]) --> B["Step 1\\nsrc/example.ts"]',
		'    B --> C([End])',
		'```',
		'',
		'## Summary',
		'Describe intent, constraints, and expected behavior.',
		'',
	].join('\n');
}
